{% set name = "xmipy" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xmipy-{{ version }}.tar.gz
  sha256: 5f86e1b63cde445853d678fd38c1ef15b4cb08ad393d91a4ad5f106ff4ba4870

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - pip
  run:
    - python >=3.8
    - bmipy
    - numpy

test:
  imports:
    - xmipy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Deltares/xmipy.git
  summary: xmipy is an extension to the bmipy Python package
  dev_url: https://github.com/Deltares/xmipy
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdhughes-usgs
