{% set name = "xmipy" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xmipy-{{ version }}.tar.gz
  sha256: e8d00947e67f72448f49e290d6a230f04e574653d09cf3dc17690109bbbe9ea5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - pip
  run:
    - python >=3.8
    - bmipy
    - numpy

test:
  imports:
    - xmipy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Deltares/xmipy.git
  summary: xmipy is an extension to the bmipy Python package
  dev_url: https://github.com/Deltares/xmipy
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jdhughes-usgs
